GET http://127.0.0.1:3333/ HTTP/1.1
Content-Type: application/json

###



POST http://127.0.0.1:61650/v1/sales/summary HTTP/1.1
Content-Type: application/json

{
    "start": "1630465200",
    "end": "1630551600",
}

