GET http://127.0.0.1:3333/ HTTP/1.1
Content-Type: application/json

###

GET http://127.0.0.1:3333/all HTTP/1.1
Content-Type: application/json

###


POST http://127.0.0.1:3333/product HTTP/1.1
Content-Type: application/json

{
    "prod": "pencil",
    "price": 2
}

